### ISSUE TITLE
Simplify and shorten the main description text

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-onboarding#124]
The description text in the main page is quite wall-of-texty. We should shorten it and keep just the essential information.

![image](https://user-images.githubusercontent.com/788293/93567870-9d204a00-f98f-11ea-917c-93e800205e59.png)

**Comment by soulhunter10737** [comment]
I would like to take this

**Comment by bfabio** [comment]
@soulhunter10737 Great, I'm assigning this to you :slightly_smiling_face:

**Comment by soulhunter10737** [comment]
@bfabio  Thank You I will do it soon and do a PR on 1st of October if it is okay.

**Comment by soulhunter10737** [comment]
@bfabio  I gave the PR
