### ISSUE TITLE
Review the FAQs

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-onboarding#160]
There are some issues in the FAQs:

* [FAQ 6](https://onboarding.developers.italia.it/faq#heading6) is a non-answer
* [FAQ 8](https://onboarding.developers.italia.it/faq#heading8) seems to contradict what we say in FAQ 9 and in the homepage
* [FAQ 16](https://onboarding.developers.italia.it/faq#heading16) and [FAQ 17](https://onboarding.developers.italia.it/faq#heading17) point back to the wrong answer

**Comment by libremente** [comment]
+1 please go ahead!
