### ISSUE TITLE
Check on input forms 

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-onboarding#28]
There is not check or sanitization on the input boxes, but just on the URL field.
When just the URL is inserted a message says:
`Abbiamo inviato il link con cui confermare l'iscrizione tramite email all'indirizzo ` with the empty remaining fields. 

# Expected behaviour
The app should check whether all the fields have been inserted and sanitize the inputs before going on.

**Comment by libremente** [comment]
Without a check, the following error is this one on the SMTP side:
`Error: No recipients defined`

**Comment by libremente** [comment]
The email is sent even without a proper name.

**Comment by sebbalex** [comment]
This is because of [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#required) "limitation".

**Comment by libremente** [comment]
Fixed by #48, closing.
