### ISSUE TITLE
Make more things configurable

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-onboarding#33]
* E-mail from
* E-mail subject
* E-mail body
* ...?

**Comment by libremente** [comment]
Right now the format of the template of the email is handled through mustache. 
See https://github.com/italia/developers-italia-onboarding/blob/5f45b1cbf515f61e7e8d33432af01bffd3aacda7/src/email-sent.js#L73 for info regarding the mail elements.

**Comment by libremente** [comment]
Fixed by #48, closing.
