### ISSUE TITLE
Improve text

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-onboarding#40]
Dobbiamo contestualizzare questa pagina con i rimandi alla documentazione sul publiccode, al funzionamento del parser, alle linee guida, al catalogo.

Poi dobbiamo spiegare che:
* il referente deve essere indicato con Nome Cognome
* "URL strumento di code hosting" deve essere l'URL della org (e non del repository né quello generico di GitHub)
* verrà inviata una PEC all'indirizzo specificato ecc. ecc.

Poi dobbiamo spiegare come fa una PA a:
* aggiungere più organizzazioni
* vedere le sue organizzazioni attuali
* modificarle
* modificare la sua denominazione

**Comment by libremente** [comment]
Primi punti fatti.
Per gli ultimi quattro:
```
    aggiungere più organizzazioni
    vedere le sue organizzazioni attuali
    modificarle
    modificare la sua denominazione
```
 non è più una questione di documentazione mancante ma di features non ancora presenti. Aprirei delle issue dedicate allo sviluppo di queste features.

**Comment by libremente** [comment]
Two new issues have been created regarding those last points. I'm closing this since the code has been improved accordingly.
