### ISSUE TITLE
Button in email message not correctly rendered

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-onboarding#56]
The button in the email sent is not correctly rendered.
As such, the user has only the alt text displayed. 
Check this behavior and understand whether it's better to remove completely the html button or not.

**Comment by sebbalex** [comment]
Tested locally and button in email is correctly rendered, could you please add more details?
See the screen attached:

![Screenshot 2019-05-27 at 11 24 05](https://user-images.githubusercontent.com/11008116/58410219-0204b200-8072-11e9-9c54-1d539aac8c45.png)

**Comment by libremente** [comment]
@sebbalex I guess we will be able to reproduce this just when a complete onboarding cycle will be closed. Or we could "test" the system by using the onboarding with the PCM ipa.

**Comment by libremente** [comment]
Attaching the `needs-more-info` label, I'd remove it from the milestone for now. What do you think @sebbalex ?

**Comment by bfabio** [comment]
Works for me.
