### ISSUE TITLE
Weird privacy box pops up

### ISSUE THREAD

**Issue by libremente** [italia/developers-italia-onboarding#59]
I see this weird spacing in the privacy box popping up from the bottom:
![Schermata da 2019-05-03 16-32-45](https://user-images.githubusercontent.com/25111463/57144462-69a44600-6dc1-11e9-8246-121a83aab36d.png)
We should fix it since it's a bit ugly @sebbalex 

FF 66 / GNU/Linux

**Comment by sebbalex** [comment]
Yes, a bit weird, it is due to  [this](https://github.com/italia/developers-italia-onboarding/blob/master/public/index.html#L163). I would remove that `<br />` and let the entire text on a single line.

**Comment by libremente** [comment]
Yes, but maybe it's also a matter of screen resolution?

**Comment by sebbalex** [comment]
I tried several resolutions, same result.

**Comment by libremente** [comment]
> I tried several resolutions, same result.

Oh OK, let's try the solution you suggested then :)
