### ISSUE TITLE
Improve search of AOO

### ISSUE THREAD

**Issue by alranel** [italia/developers-italia-onboarding#72]
We noticed that it's not easy to locate a PEC address linked to an office (AOO) because of a few issues that break the experience:

* PEC addresses are indexed only as keywords but they should be also searchable as full-text strings (this way "@pec.torvergata.it" would be listed also when searching "torvergata");
* office codes are case sensitive ("dicii" != "DICII") but they should be searchable as case-insensitive;
* The name of the root entity (for example "Universita' degli Studi di Roma 'Tor Vergata'") is not displayed along with its offices' names (for example "Dipartimento..") and it's not used as a search field. So if I search for "Tor Vergata" I don't see its departments listed because of course there's no "Tor Vergata" string in their names. We should search both in the office names and in the root entity names.
* The office names are apparently indexed as keywords and not as full-text; this might because by the fact that I didn't recreate the mapping after implementing #47).

**Comment by alranel** [comment]
If impleenting these things we should consider ditching the nested mapping and using a flat list that we can import from this file:
https://www.indicepa.gov.it/public-services/opendata-read-service.php?dstype=FS&filename=pec.txt

Apparently, that file contains everything we need except for "tipo_amm" which the crawler could easily join from the other CSV files.

**Comment by sebbalex** [comment]
It might have more sense to use a "flattened" version since it matches all of our use cases. We could lose `office_code` which is not a big deal perhaps.
Ex:
`PCM	Commissario straordinario per l'attuazione dell'Agenda digitale	UO	Presidenza del Consiglio dei Ministri, Ministeri e Avvocatura dello Stato	Lazio	RM	Roma	teamdigitale@pec.governo.it	pec`

**Comment by alranel** [comment]
As discussed, share the new Elasticsearch mapping with me and I'll have it populated by the crawler.

**Comment by alranel** [comment]
Also, let's include the fiscal code since we can get it easily.

**Comment by alranel** [comment]
And let's include sito_istituzionale needed by https://github.com/italia/developers-italia-backend/issues/91

**Comment by alranel** [comment]
New mapping by @sebbalex:

```json
{
    "settings": {
      "index": {
        "analysis": {
          "filter": {},
          "analyzer": {
            "autocomplete": {
              "tokenizer": "autocomplete",
              "filter": "lowercase"
            },
            "autocomplete_search": {
              "tokenizer": "lowercase"
            }
          },
          "tokenizer": {
            "autocomplete": {
              "type": "edge_ngram",
              "min_gram": 2,
              "max_gram": 20,
              "token_chars": [
                "letter"
              ]
            }
          }
        }
      }
    },
    "mappings": {
      "pa": {
        "dynamic": "strict",
        "properties": {
          "ipa": {
            "type": "text",
            "analyzer": "autocomplete",
            "search_analyzer": "autocomplete_search"
          },
          "description": {
            "type": "text",
            "analyzer": "autocomplete",
            "search_analyzer": "autocomplete_search"
          },
          "pec": {
            "type": "text",
            "analyzer": "autocomplete",
            "search_analyzer": "autocomplete_search"
          },
          "type": {
            "type": "keyword"
          },
          "cf": {
            "type": "keyword"
          }
        }
      }
    }
  }
```

**Comment by alranel** [comment]
Implemented in https://github.com/italia/developers-italia-backend/pull/98

I already populated a `indicepa_pec` index with this new logic so that we can test that the new structure works well for us. I'll merge that PR after we are sure that we want to switch.
